fabric run critic_train_lightning.py \
    --backend 'vllm' \
	--actor_path '/lus/eagle/projects/FoundEpidem/bhsu/2024_research/models/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/e1945c40cd546c78e41f1151f4db032b271faeaa' \
	--actor_model_type 'llama-3' \
    --critic_path '/lus/eagle/projects/FoundEpidem/bhsu/2024_research/models/models--Salesforce--SFR-Embedding-Mistral/snapshots/938c560d1c236aa563b2dbdf084f28ab28bccb11'\
    --logging_level 'info' \
    --logging_save_path 'debug_llama_3_logging.log' \
    --log_wandb_offline False \
    --gamma 0.99 \
    --learning_rate 1e-4 \
    --num_epochs 10 \
    --num_episodes 10 \
    --global_buffer_size 2000 \
    --collection_batch_size 16 \
    --train_batch_size 4 \
    --checkpoints_total_limit 10 \
    --checkpointing_steps 2 \
    --output_dir 'actor-finetuned-critic'\
    --devices 1 \
    --accelerator 'cuda' \
	--strategy 'ddp'
