#!/bin/bash -l
#PBS -l select=10
#PBS -A FoundEpidem
#PBS -l walltime=3:00:00
#PBS -l filesystems=home:eagle
#PBS -q prod

### Name of your session
#PBS -N SMALL_Critic_Finetuning

### Controlling output of application 
#PBS -k doe
#PBS -o ./output_logs_critic_finetune_small
#PBS -e ./error_logs_critic_finetune_small

### email notification
#PBS -m be
#PBS -M bhsu@anl.gov

echo "Changing to current working directory: {$PBS_O_WORKDIR}"
### directions 
module load conda/2024-04-29
conda activate lactchain4
cd $PBS_O_WORKDIR

## Running actual script
fabric run critic_train_lightning.py \
    --actor_path '/lus/eagle/projects/FoundEpidem/bhsu/2024_research/models/models--mistralai--Mistral-7B-Instruct-v0.3/snapshots/83e9aa141f2e28c82232fea5325f54edf17c43de'\
	--actor_model_type 'mistral-7b' \
    --critic_path '/lus/eagle/projects/FoundEpidem/bhsu/2024_research/models/models--Salesforce--SFR-Embedding-Mistral/snapshots/938c560d1c236aa563b2dbdf084f28ab28bccb11'\
    --logging_level 'info' \
    --logging_save_path 'mistral_7b_logging_small.log' \
    --log_wandb_offline False \
    --gamma 0.99 \
    --learning_rate 1e-4 \
    --num_epochs 10 \
    --num_episodes 10 \
    --global_buffer_size 10000 \
    --collection_batch_size 8 \
    --train_batch_size 64 \
    --checkpoints_total_limit 10 \
    --checkpointing_steps 10 \
    --output_dir 'finetuned-critic'\
    --devices 4 \
    --accelerator 'cuda' \
	--strategy 'ddp'